language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
  - 'lts/*'
script:
  - yarn build
branches:
  only:
    - master
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - yarn semantic-release
