language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
script:
  - yarn build
after_success:
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  only:
    - master
